# Generated by Django 4.2.11 on 2024-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="AccountBalance",
        ),
    ]
